image: docker:latest

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
  - docker info || true
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY || true

build:
  tags:
    - dedi
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t eval -f Dockerfile .
    - docker tag eval $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
